{
  "uid" : "b1f0f47e3a9bb1a4",
  "name" : "test_transfer_to_self_no_approval",
  "fullName" : "tests.brownie.token.tests.test_transferFrom#test_transfer_to_self_no_approval",
  "historyId" : "e64c769fe7fbe0824bd4983651fa94bc",
  "time" : {
    "start" : 1638414589656,
    "stop" : 1638414589656,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='test3-solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe4c513340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
  "statusTrace" : "brownie_project = <Project 'TokenProject'>\naccounts = <brownie.network.account.Accounts object at 0x7fe280d0b370>\n\n    @pytest.fixture(scope=\"module\")\n    def token(brownie_project, accounts):\n>       return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n\ntests/brownie/token/tests/conftest.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py:600: in __call__\n    return tx[\"from\"].deploy(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:508: in deploy\n    receipt, exc = self._make_transaction(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:725: in _make_transaction\n    raise VirtualMachineError(e) from None\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = VirtualMachineError(ValueError(\"Gas estimation failed: 'HTTPConnectionPool(host='test3-solana', port=8899): Max retrie... resolution'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.\"))\nexc = \"Gas estimation failed: 'HTTPConnectionPool(host='test3-solana', port=8899): Max retries exceeded with url: / (Caused ...me resolution'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.\"\n\n    def __init__(self, exc: ValueError) -> None:\n        try:\n            exc = exc.args[0]\n        except Exception:\n            pass\n    \n        if isinstance(exc, dict) and \"message\" in exc:\n            if \"data\" not in exc:\n                raise ValueError(exc[\"message\"]) from None\n    \n            self.message: str = exc[\"message\"].rstrip(\".\")\n    \n            if isinstance(exc[\"data\"], str):\n                # handle parity exceptions - this logic probably is not perfect\n                if \"0x08c379a0\" in exc[\"data\"]:\n                    revert_type, err_msg = [i.strip() for i in exc[\"data\"].split(\"0x08c379a0\", 1)]\n                    err_msg = eth_abi.decode_abi([\"string\"], HexBytes(err_msg))\n                    err_msg = f\"{revert_type} '{err_msg}'\"\n                elif exc[\"data\"].endswith(\"0x\"):\n                    err_msg = exc[\"data\"][:-2].strip()\n                else:\n                    err_msg = exc[\"data\"]\n                raise ValueError(f\"{self.message}: {err_msg}\") from None\n    \n            try:\n                txid, data = next((k, v) for k, v in exc[\"data\"].items() if k.startswith(\"0x\"))\n            except StopIteration:\n                raise ValueError(exc[\"message\"]) from None\n    \n            self.txid: str = txid\n            self.source: str = \"\"\n            self.revert_type: str = data[\"error\"]\n            self.pc: Optional[str] = data.get(\"program_counter\")\n            if self.pc and self.revert_type == \"revert\":\n                self.pc -= 1\n    \n            self.revert_msg: Optional[str] = data.get(\"reason\")\n            self.dev_revert_msg = brownie.project.build._get_dev_revert(self.pc)\n            if self.revert_msg is None and self.revert_type in (\"revert\", \"invalid opcode\"):\n                self.revert_msg = self.dev_revert_msg\n            elif self.revert_msg == \"Failed assertion\":\n                self.revert_msg = self.dev_revert_msg or self.revert_msg\n    \n        else:\n>           raise ValueError(str(exc)) from None\nE           ValueError: Gas estimation failed: 'HTTPConnectionPool(host='test3-solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe4c513340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.\n\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py:121: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : true,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "configure_neon_network",
    "time" : {
      "start" : 1638414565014,
      "stop" : 1638414565015,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "brownie_project",
    "time" : {
      "start" : 1638414566601,
      "stop" : 1638414584930,
      "duration" : 18329
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "accounts",
    "time" : {
      "start" : 1638414585447,
      "stop" : 1638414585723,
      "duration" : 276
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "setup_env",
    "time" : {
      "start" : 1638414585447,
      "stop" : 1638414585447,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "token",
    "time" : {
      "start" : 1638414588098,
      "stop" : 1638414588438,
      "duration" : 340
    },
    "status" : "broken",
    "statusMessage" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='test3-solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe4c513340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.\n",
    "statusTrace" : "  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/neon-compatibility/neon-compatibility/tests/brownie/token/tests/conftest.py\", line 49, in token\n    return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py\", line 600, in __call__\n    return tx[\"from\"].deploy(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 508, in deploy\n    receipt, exc = self._make_transaction(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 725, in _make_transaction\n    raise VirtualMachineError(e) from None\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py\", line 121, in __init__\n    raise ValueError(str(exc)) from None\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "accounts::0",
    "time" : {
      "start" : 1638414589948,
      "stop" : 1638414589948,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Brownie"
  }, {
    "name" : "parentSuite",
    "value" : "tests.brownie.token.tests"
  }, {
    "name" : "suite",
    "value" : "test_transferFrom"
  }, {
    "name" : "host",
    "value" : "fv-az123-322"
  }, {
    "name" : "thread",
    "value" : "3469-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.brownie.token.tests.test_transferFrom"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 12,
        "broken" : 5,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "30cf52ae96b09569",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/147//#testresult/30cf52ae96b09569",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638399379226,
          "stop" : 1638399381453,
          "duration" : 2227
        }
      }, {
        "uid" : "f2c37b6001be2f2a",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/2//#testresult/f2c37b6001be2f2a",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638376010846,
          "stop" : 1638376012718,
          "duration" : 1872
        }
      }, {
        "uid" : "6cae80071f23459c",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/146//#testresult/6cae80071f23459c",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638363670307,
          "stop" : 1638363672477,
          "duration" : 2170
        }
      }, {
        "uid" : "38d92138cbb09830",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/145//#testresult/38d92138cbb09830",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638328245472,
          "stop" : 1638328246921,
          "duration" : 1449
        }
      }, {
        "uid" : "2bb1eb4b800b03f3",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/143//#testresult/2bb1eb4b800b03f3",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638318715755,
          "stop" : 1638318717789,
          "duration" : 2034
        }
      }, {
        "uid" : "10c0f2542e382c2e",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/141//#testresult/10c0f2542e382c2e",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638285888137,
          "stop" : 1638285890236,
          "duration" : 2099
        }
      }, {
        "uid" : "c5590b16cffce40d",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/137//#testresult/c5590b16cffce40d",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638265823855,
          "stop" : 1638265825996,
          "duration" : 2141
        }
      }, {
        "uid" : "1a6a2a0f585221e7",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/140//#testresult/1a6a2a0f585221e7",
        "status" : "broken",
        "statusDetails" : "ValueError: Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction",
        "time" : {
          "start" : 1638269198426,
          "stop" : 1638269198426,
          "duration" : 0
        }
      }, {
        "uid" : "68566dd020760937",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/138//#testresult/68566dd020760937",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='test3-solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4107a10c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1638265727533,
          "stop" : 1638265727533,
          "duration" : 0
        }
      }, {
        "uid" : "9336ff4a1c001ee5",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/136//#testresult/9336ff4a1c001ee5",
        "status" : "broken",
        "statusDetails" : "ValueError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.",
        "time" : {
          "start" : 1638246927708,
          "stop" : 1638246927708,
          "duration" : 0
        }
      }, {
        "uid" : "25ba6c983afc3e11",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/135//#testresult/25ba6c983afc3e11",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638241859851,
          "stop" : 1638241861857,
          "duration" : 2006
        }
      }, {
        "uid" : "5f4c9e10756b5e46",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/134//#testresult/5f4c9e10756b5e46",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638232212438,
          "stop" : 1638232214555,
          "duration" : 2117
        }
      }, {
        "uid" : "e4f411183eb38d32",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/133//#testresult/e4f411183eb38d32",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638219699171,
          "stop" : 1638219701326,
          "duration" : 2155
        }
      }, {
        "uid" : "ff931b689dbcc7ac",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/131//#testresult/ff931b689dbcc7ac",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638203564924,
          "stop" : 1638203566320,
          "duration" : 1396
        }
      }, {
        "uid" : "e62ddfb97480eef4",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/129//#testresult/e62ddfb97480eef4",
        "status" : "failed",
        "statusDetails" : "AssertionError: Transaction did not revert",
        "time" : {
          "start" : 1638200080801,
          "stop" : 1638200082527,
          "duration" : 1726
        }
      }, {
        "uid" : "2adeec2b9b33b7cb",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/128//#testresult/2adeec2b9b33b7cb",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1638198575483,
          "stop" : 1638198575483,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "b1f0f47e3a9bb1a4.json",
  "parameterValues" : [ ]
}