{
  "uid" : "56147c81eb80332e",
  "name" : "test_insufficient_approval",
  "fullName" : "tests.brownie.token.tests.test_transferFrom#test_insufficient_approval",
  "historyId" : "0ae63a08126a8f0616f222dcfe6ba70d",
  "time" : {
    "start" : 1642028351504,
    "stop" : 1642028351504,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ValueError: connection already closed",
  "statusTrace" : "brownie_project = <Project 'TokenProject'>\naccounts = <brownie.network.account.Accounts object at 0x7f654f579f70>\n\n    @pytest.fixture(scope=\"module\")\n    def token(brownie_project, accounts):\n>       return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n\ntests/brownie/token/tests/conftest.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py:600: in __call__\n    return tx[\"from\"].deploy(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:508: in deploy\n    receipt, exc = self._make_transaction(\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py:725: in _make_transaction\n    raise VirtualMachineError(e) from None\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = VirtualMachineError(ValueError({'code': -32000, 'message': 'connection already closed'}))\nexc = {'code': -32000, 'message': 'connection already closed'}\n\n    def __init__(self, exc: ValueError) -> None:\n        try:\n            exc = exc.args[0]\n        except Exception:\n            pass\n    \n        if isinstance(exc, dict) and \"message\" in exc:\n            if \"data\" not in exc:\n>               raise ValueError(exc[\"message\"]) from None\nE               ValueError: connection already closed\n\n../../../.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py:85: ValueError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "configure_neon_network",
    "time" : {
      "start" : 1642028329677,
      "stop" : 1642028329677,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "brownie_project",
    "time" : {
      "start" : 1642028330735,
      "stop" : 1642028346618,
      "duration" : 15883
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "accounts",
    "time" : {
      "start" : 1642028347418,
      "stop" : 1642028347686,
      "duration" : 268
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "setup_env",
    "time" : {
      "start" : 1642028347418,
      "stop" : 1642028347418,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "token",
    "time" : {
      "start" : 1642028350181,
      "stop" : 1642028350678,
      "duration" : 497
    },
    "status" : "broken",
    "statusMessage" : "ValueError: connection already closed\n",
    "statusTrace" : "  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/neon-compatibility/neon-compatibility/tests/brownie/token/tests/conftest.py\", line 49, in token\n    return brownie_project.Token.deploy(\"Test Token\", \"TST\", 18, 1e21, {'from': accounts[0]})\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/contract.py\", line 600, in __call__\n    return tx[\"from\"].deploy(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 508, in deploy\n    receipt, exc = self._make_transaction(\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/network/account.py\", line 725, in _make_transaction\n    raise VirtualMachineError(e) from None\n  File \"/home/runner/.local/share/virtualenvs/neon-compatibility-g882AfFF/lib/python3.8/site-packages/brownie/exceptions.py\", line 85, in __init__\n    raise ValueError(exc[\"message\"]) from None\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  } ],
  "afterStages" : [ {
    "name" : "accounts::0",
    "time" : {
      "start" : 1642028380425,
      "stop" : 1642028380425,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Brownie"
  }, {
    "name" : "parentSuite",
    "value" : "tests.brownie.token.tests"
  }, {
    "name" : "suite",
    "value" : "test_transferFrom"
  }, {
    "name" : "host",
    "value" : "fv-az135-192"
  }, {
    "name" : "thread",
    "value" : "3629-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.brownie.token.tests.test_transferFrom"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 88,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 88
      },
      "items" : [ {
        "uid" : "b63c7707678bcbaf",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/474//#testresult/b63c7707678bcbaf",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642025673657,
          "stop" : 1642025673657,
          "duration" : 0
        }
      }, {
        "uid" : "84d94131d959e0af",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/472//#testresult/84d94131d959e0af",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642018239481,
          "stop" : 1642018239481,
          "duration" : 0
        }
      }, {
        "uid" : "396dc3d650030cb0",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/471//#testresult/396dc3d650030cb0",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642015605310,
          "stop" : 1642015605310,
          "duration" : 0
        }
      }, {
        "uid" : "aa084cf28a74e0d6",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/470//#testresult/aa084cf28a74e0d6",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642014231438,
          "stop" : 1642014231438,
          "duration" : 0
        }
      }, {
        "uid" : "c983f51cfcd99dde",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/469//#testresult/c983f51cfcd99dde",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642012912911,
          "stop" : 1642012912911,
          "duration" : 0
        }
      }, {
        "uid" : "c8f69fa4fd79e3ea",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/468//#testresult/c8f69fa4fd79e3ea",
        "status" : "broken",
        "statusDetails" : "ValueError: connection already closed",
        "time" : {
          "start" : 1642011423786,
          "stop" : 1642011423786,
          "duration" : 0
        }
      }, {
        "uid" : "8470ab4acf9689c7",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/466//#testresult/8470ab4acf9689c7",
        "status" : "broken",
        "statusDetails" : "OverflowError: approve '-1' - -1 is outside allowable range for uint256",
        "time" : {
          "start" : 1641998035856,
          "stop" : 1641998036083,
          "duration" : 227
        }
      }, {
        "uid" : "5648fe830d9a1144",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/465//#testresult/5648fe830d9a1144",
        "status" : "broken",
        "statusDetails" : "OverflowError: approve '-1' - -1 is outside allowable range for uint256",
        "time" : {
          "start" : 1641993797374,
          "stop" : 1641993797588,
          "duration" : 214
        }
      }, {
        "uid" : "228fdeb14494b3d7",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/464//#testresult/228fdeb14494b3d7",
        "status" : "broken",
        "statusDetails" : "OverflowError: approve '-1' - -1 is outside allowable range for uint256",
        "time" : {
          "start" : 1641991050878,
          "stop" : 1641991051069,
          "duration" : 191
        }
      }, {
        "uid" : "94be5ec4ea4aeadf",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/463//#testresult/94be5ec4ea4aeadf",
        "status" : "broken",
        "statusDetails" : "OverflowError: approve '-1' - -1 is outside allowable range for uint256",
        "time" : {
          "start" : 1641986395730,
          "stop" : 1641986395871,
          "duration" : 141
        }
      }, {
        "uid" : "c6cf531b86d04bea",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/461//#testresult/c6cf531b86d04bea",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1895fe5e80>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641982479214,
          "stop" : 1641982479214,
          "duration" : 0
        }
      }, {
        "uid" : "686592d6fd201afd",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/460//#testresult/686592d6fd201afd",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f189460db20>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641980268252,
          "stop" : 1641980268252,
          "duration" : 0
        }
      }, {
        "uid" : "ec4566601bb4db29",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/459//#testresult/ec4566601bb4db29",
        "status" : "broken",
        "statusDetails" : "OverflowError: approve '-1' - -1 is outside allowable range for uint256",
        "time" : {
          "start" : 1641975867958,
          "stop" : 1641975868158,
          "duration" : 200
        }
      }, {
        "uid" : "7732d7c5f933e6b1",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/458//#testresult/7732d7c5f933e6b1",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f189a842400>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641974828339,
          "stop" : 1641974828339,
          "duration" : 0
        }
      }, {
        "uid" : "3886ea643d3e8b50",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/457//#testresult/3886ea643d3e8b50",
        "status" : "broken",
        "statusDetails" : "ValueError: Gas estimation failed: 'HTTPConnectionPool(host='10.2.0.2', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1896042940>: Failed to establish a new connection: [Errno 111] Connection refused'))'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.",
        "time" : {
          "start" : 1641974206933,
          "stop" : 1641974206933,
          "duration" : 0
        }
      }, {
        "uid" : "6ccfa83fd1c31aa1",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/456//#testresult/6ccfa83fd1c31aa1",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.night.stand.neontest.xyz', port=80): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1641958013275,
          "stop" : 1641958013275,
          "duration" : 0
        }
      }, {
        "uid" : "b8421c1a1e401944",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/455//#testresult/b8421c1a1e401944",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.night.stand.neontest.xyz', port=80): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1641952209300,
          "stop" : 1641952209300,
          "duration" : 0
        }
      }, {
        "uid" : "90fc132d0c3a3a45",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/454//#testresult/90fc132d0c3a3a45",
        "status" : "broken",
        "statusDetails" : "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='proxy.night.stand.neontest.xyz', port=80): Read timed out. (read timeout=30)",
        "time" : {
          "start" : 1641950686943,
          "stop" : 1641950686943,
          "duration" : 0
        }
      }, {
        "uid" : "138eb57d88396da",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/453//#testresult/138eb57d88396da",
        "status" : "broken",
        "statusDetails" : "ValueError: ['Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io invoke [1]', 'Program log: program/src/storage_account.rs:76', 'Program log: program/src/account_data.rs:225', 'Program log: program/src/entrypoint.rs:1251 : Invalid Ethereum transaction nonce: acc 21, trx 20', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io consumed 51427 of 500000 compute units', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io failed: invalid program argument', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io invoke [1]', 'Program log: program/src/storage_account.rs:76', 'Program log: program/src/account_data.rs:225', 'Program log: program/src/entrypoint.rs:1251 : Invalid Ethereum transaction nonce: acc 21, trx 20', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io consumed 51427 of 500000 compute units', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io failed: invalid program argument', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io invoke [1]', 'Program log: program/src/storage_account.rs:76', 'Program log: program/src/account_data.rs:225', 'Program log: program/src/entrypoint.rs:1251 : Invalid Ethereum transaction nonce: acc 21, trx 20', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io consumed 51427 of 500000 compute units', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io failed: invalid program argument', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io invoke [1]', 'Program log: program/src/storage_account.rs:76', 'Program log: program/src/account_data.rs:225', 'Program log: program/src/entrypoint.rs:1251 : Invalid Ethereum transaction nonce: acc 21, trx 20', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io consumed 51427 of 500000 compute units', 'Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io failed: invalid program argument']",
        "time" : {
          "start" : 1641947815957,
          "stop" : 1641947815957,
          "duration" : 0
        }
      }, {
        "uid" : "fdfb2de59091f491",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/452//#testresult/fdfb2de59091f491",
        "status" : "broken",
        "statusDetails" : "OverflowError: approve '-1' - -1 is outside allowable range for uint256",
        "time" : {
          "start" : 1641871098999,
          "stop" : 1641871099151,
          "duration" : 152
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "56147c81eb80332e.json",
  "parameterValues" : [ ]
}